In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
arr6=np.arange(0,11,2)
arr6

array([ 0,  2,  4,  6,  8, 10])

In [10]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [11]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [12]:
arr1

array([1, 2, 3, 4, 5])

In [27]:
arr1.shape # Shape of array

(5,)

In [28]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr2.shape

(2, 3)

In [35]:
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) # 3D-Array
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [36]:
arr9.shape

(2, 2, 2)

In [37]:
arr9.ndim # show dimensional of array

3

In [38]:
arr2.ndim

2

In [39]:
arr1.ndim

1

In [42]:
arr1.size # No.of items

5

In [43]:
arr9.size

8

In [44]:
arr9.itemsize

8

In [45]:
arr7.itemsize

8

In [46]:
arr9.dtype

dtype('int64')

In [47]:
arr7.dtype

dtype('float64')

In [48]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])