In [13]:
import numpy as np

In [14]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([4,5,6,7,8,9])

In [15]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [16]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [17]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [18]:
arr2>3

array([ True,  True,  True,  True,  True,  True])

In [19]:
arr3=np.arange(6).reshape(2,3)
arr4=np.arange(6,12).reshape(3,2)

In [20]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [21]:
arr3

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [23]:
arr1.dot(arr2)

np.int64(154)

In [24]:
arr4.max()

np.int64(11)

In [25]:
arr4.min()

np.int64(6)

In [26]:
arr4.min(axis=0)

array([6, 7])

In [27]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [29]:
arr4.sum()

np.int64(51)

In [30]:
arr4.sum(axis=0)

array([24, 27])

In [31]:
arr4.sum(axis=1)

array([13, 17, 21])

In [32]:
arr4.mean()

np.float64(8.5)

In [33]:
arr4.std()

np.float64(1.707825127659933)

In [34]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [35]:
np.median(arr4)

np.float64(8.5)

In [36]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])