In [1]:
import numpy as np

In [9]:
arr1=np.arange(6,12).reshape(3,2)
arr2=np.arange(6).reshape(2,3)

In [6]:
arr1.ndim

2

In [5]:
arr1.ravel()

array([ 6,  7,  8,  9, 10, 11])

In [7]:
arr1

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [8]:
arr1.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [10]:
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
arr3=np.arange(12,18).reshape(2,3)

In [12]:
arr3

array([[12, 13, 14],
       [15, 16, 17]])

In [13]:
np.hstack((arr2,arr3))

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [14]:
np.vstack((arr2,arr3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [12, 13, 14],
       [15, 16, 17]])

In [15]:
np.hsplit(arr2, 3)

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [16]:
np.vsplit(arr2, 2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]