In [1]:
import numpy as np

In [2]:
arr=np.random.randint(low=1,high=100,size=20).reshape(4,5)
arr

array([[22, 36, 26, 34, 34],
       [ 3, 40, 49,  9,  7],
       [68, 91, 70, 96, 15],
       [33, 16, 56, 20, 23]], dtype=int32)

In [4]:
arr[0][2]

np.int32(26)

In [5]:
arr>50

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True, False],
       [False, False,  True, False, False]])

In [7]:
# Indexing using Boolean Arrays
arr[arr>50]

array([68, 91, 70, 96, 56], dtype=int32)

In [8]:
arr[(arr>50) & (arr%2!=0)]

array([91], dtype=int32)

In [9]:
arr[(arr>50) & (arr%2!=0)]=0

In [10]:
arr

array([[22, 36, 26, 34, 34],
       [ 3, 40, 49,  9,  7],
       [68,  0, 70, 96, 15],
       [33, 16, 56, 20, 23]], dtype=int32)