In [1]:
import numpy as np

In [2]:
np.random.random()

0.026918564592099625

In [3]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [4]:
np.random.uniform(1,100)

72.31212485077366

In [6]:
np.random.uniform(1,100,10).reshape(5,2)

array([[21.24077272, 87.9336262 ],
       [ 3.71137173, 67.37628351],
       [42.31317543, 56.31029302],
       [14.89830692, 20.61204742],
       [80.2737123 , 96.857896  ]])

In [9]:
np.random.randint(1,10,15).reshape(3,5)

array([[4, 9, 8, 4, 7],
       [6, 2, 4, 5, 9],
       [2, 5, 1, 4, 3]], dtype=int32)

In [11]:
a=np.random.randint(1,10,6)
a

array([7, 4, 8, 8, 5, 6], dtype=int32)

In [12]:
np.max(a)

np.int32(8)

In [13]:
np.min(a)

np.int32(4)

In [14]:
np.argmax(a)

np.int64(2)

In [15]:
a[np.argmax(a)]

np.int32(8)

In [16]:
np.argmin(a)

np.int64(1)

In [17]:
a[np.argmin(a)]

np.int32(4)

In [18]:
a

array([7, 4, 8, 8, 5, 6], dtype=int32)

In [19]:
a[a%2==1]=-1
a

array([-1,  4,  8,  8, -1,  6], dtype=int32)

In [22]:
a=np.random.randint(1,50,6)
a

array([16, 48, 24, 26,  8, 29], dtype=int32)

In [23]:
np.where(a%2==1,-1,a)

array([16, 48, 24, 26,  8, -1], dtype=int32)

In [24]:
a

array([16, 48, 24, 26,  8, 29], dtype=int32)

In [25]:
out=np.where(a%2==1,-1,a)
out

array([16, 48, 24, 26,  8, -1], dtype=int32)

In [26]:
a=np.random.randint(1,50,10)
a

array([11, 47, 33, 25, 24,  2, 14,  4,  1, 14], dtype=int32)

In [28]:
a=np.sort(a)
a

array([ 1,  2,  4, 11, 14, 14, 24, 25, 33, 47], dtype=int32)

In [29]:
np.percentile(a,25)

np.float64(5.75)

In [30]:
np.percentile(a,50)

np.float64(14.0)

In [32]:
np.percentile(a,100)

np.float64(47.0)